name: API Trigger

on:
  workflow_dispatch:
    inputs:
      task:
        description: '要执行的任务'
        required: true
        type: choice
        options:
          - 'test_message'
          - 'test_new_stock'
          - 'test_stock_pool'
          - 'test_execute'
          - 'test_reset'
          - 'run_new_stock_info'
          - 'push_strategy'
          - 'update_stock_pool'
          - 'crawl_daily'
          - 'crawl_intraday'
          - 'cleanup'

jobs:
  trigger-main-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main workflow
        uses: actions/github-script@v7
        with:
          # 修复1: 更正参数名为 github-token
          github-token: ${{ secrets.GITH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              # 修复2: 移除 .yml 扩展名
              workflow_id: 'schedule',
              ref: 'main',
              inputs: {
                task: '${{ inputs.task }}'
              }
            })
