name: Initialize Data Directories

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  init-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # 确保能推送变更
      
      - name: Check if data directory exists
        id: check_data
        run: |
          if [ ! -d "data" ]; then
            echo "DATA_EXISTS=false" >> $GITHUB_OUTPUT
          else
            echo "DATA_EXISTS=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create data directories
        if: steps.check_data.outputs.DATA_EXISTS == 'false'
        run: |
          mkdir -p data/raw
          mkdir -p data/stock_pool
          mkdir -p data/trade_log
          mkdir -p data/error_log
          mkdir -p data/new_stock
          # 创建占位文件确保Git能跟踪空目录
          touch data/.gitkeep
          touch data/raw/.gitkeep
          touch data/stock_pool/.gitkeep
          touch data/trade_log/.gitkeep
          touch data/error_log/.gitkeep
          touch data/new_stock/.gitkeep
      
      - name: Commit and push data directories
        if: steps.check_data.outputs.DATA_EXISTS == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Initialize data directories" || echo "No changes to commit"
          git push || echo "Failed to push changes"
      
      - name: Verify directories
        run: |
          echo "检查目录是否创建成功:"
          ls -la data/
          ls -la data/raw/
          ls -la data/stock_pool/
          ls -la data/trade_log/
          ls -la data/error_log/
          ls -la data/new_stock/
