name: ETF Strategy Scheduler

on:
  schedule:
    # 每个交易日 9:31 爬取当天新股申购、新上市股票信息 (北京时间 UTC+8)
    - cron: '31 1 * * 1-5' # UTC 1:31 = 北京时间 9:31
    
    # 每个交易日 9:45 推送新股申购和新上市股票信息 (北京时间 UTC+8)
    - cron: '45 1 * * 1-5' # UTC 1:45 = 北京时间 9:45
    
    # 每个交易日 9:55 爬取当天ETF交易数据 (北京时间 UTC+8)
    - cron: '55 1 * * 1-5' # UTC 1:55 = 北京时间 9:55
    
    # 每个交易日 13:00 套利扫描、股票池策略计算与推送 (北京时间 UTC+8)
    - cron: '0 5 * * 1-5' # UTC 5:00 = 北京时间 13:00
    
    # 每个交易日 16:00 爬取日线数据 (北京时间 UTC+8)
    - cron: '0 8 * * 1-5' # UTC 8:00 = 北京时间 16:00
    
    # 每天 00:00 清理旧数据 (北京时间 UTC+8)
    - cron: '0 16 * * *' # UTC 16:00 = 北京时间 00:00
    
    # 断点续爬任务（每2小时执行一次）
    - cron: '0 */2 * * *' # 每2小时执行一次

  # 允许手动触发
  workflow_dispatch:
    inputs:
      task:
        description: '选择要执行的任务'
        required: true
        type: choice
        options:
          - 'test_message'      				#【T01】手动推送微信消息
          - 'test_new_stock'    			#【T07】手动推送新股信息
          - 'test_new_stock_listings'		#【T08】手动推送新上市交易股票信息
          - 'test_stock_pool'    			#【T04】手动推送当前股票池
          - 'test_execute'				#【T05】手动执行策略并推送结果
          - 'test_reset'					#【T06】手动重置所有仓位（测试用）
          - 'test_arbitrage'				#【T09】手动套利扫描
          - 'crawl_new_stock'			#【T10】手动爬取新股申购和新上市股票信息
          - 'crawl_intraday'				#【T11】手动爬取当天ETF交易数据
          - 'push_new_stock'				#【T12】手动推送新股申购和新上市股票信息
          - 'arbitrage-scan'				#【T13】手动套利扫描
          - 'push_strategy'				#【T14】手动推送策略信号
          - 'crawl_daily'				#【T15】手动爬取日线数据
          - 'cleanup'					#【T16】手动清理旧数据
          - 'resume_crawl'				#【T17】手动断点续爬

jobs:
  # 通用测试任务处理程序 - 关键组件
  run-test-tasks:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run test task
        env:
          TASK: ${{ github.event.inputs.task }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新测试任务数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Test task execution completed successfully!"

  # 9:31 AM：爬取当天新股申购、新上市股票信息
  crawl-new-stock:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '31 1 * * 1-5'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
          echo "Is trading day: $(date '+%u')"
      
      - name: Run strategy
        env:
          TASK: 'crawl_new_stock'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新新股数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "New stock info execution completed successfully!"

  # 9:45 AM：推送新股申购和新上市股票信息
  push-new-stock:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '45 1 * * 1-5'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run strategy
        env:
          TASK: 'push_new_stock'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新新股信息 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "New stock info push execution completed successfully!"

  # 9:55 AM：爬取当天ETF交易数据
  crawl-intraday:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '55 1 * * 1-5'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Current UTC hour: $(date -u '+%H')"
          echo "Event schedule: ${{ github.event.schedule }}"
      
      - name: Run strategy
        env:
          TASK: 'crawl_intraday'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动爬取ETF交易数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Intraday crawl execution completed successfully!"

  # 13:00 PM：套利扫描、股票池策略计算与推送
  arbitrage-and-strategy:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 5 * * 1-5'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run arbitrage scan
        env:
          TASK: 'arbitrage-scan'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动扫描套利机会 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"
      
      - name: Run strategy push
        env:
          TASK: 'push_strategy'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动推送策略 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Arbitrage scan and strategy push execution completed successfully!"

  # 16:00 PM：爬取日线数据
  crawl-daily:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 8 * * 1-5'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Is weekday? $([ $(date -u '+%u') -le 5 ] && echo 'Yes' || echo 'No')"
      
      - name: Run strategy
        env:
          TASK: 'crawl_daily'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动爬取日线数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Daily crawl execution completed successfully!"

  # 00:00 AM：清理旧数据
  cleanup:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 16 * * *'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Cleanup task triggered at $(date -u)"
      
      - name: Run strategy
        env:
          TASK: 'cleanup'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动清理旧数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Cleanup execution completed successfully!"

  # 断点续爬任务（每2小时执行一次，仅在非交易时间）
  resume-crawl:
    if: ${{ 
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 */2 * * *'))
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
