name: ETF Strategy Scheduler

on:
  schedule:
    # 每个交易日 9:31 爬取当天新股申购、新上市股票信息 (北京时间 UTC+8)
    - cron: '31 1 * * 1-5' # UTC 1:31 = 北京时间 9:31
    
    # 每个交易日 9:45 推送新股申购和新上市股票信息 (北京时间 UTC+8)
    - cron: '45 1 * * 1-5' # UTC 1:45 = 北京时间 9:45
    
    # 每个交易日 9:55 爬取当天ETF交易数据 (北京时间 UTC+8)
    - cron: '55 1 * * 1-5' # UTC 1:55 = 北京时间 9:55
    
    # 每个交易日 13:00 套利扫描、股票池策略计算与推送 (北京时间 UTC+8)
    - cron: '0 5 * * 1-5' # UTC 5:00 = 北京时间 13:00
    
    # 每个交易日 16:00 爬取日线数据 (北京时间 UTC+8)
    - cron: '0 8 * * 1-5' # UTC 8:00 = 北京时间 16:00
    
    # 每天 00:00 清理旧数据 (北京时间 UTC+8)
    - cron: '0 16 * * *' # UTC 16:00 = 北京时间 00:00
    
    # 断点续爬任务（每2小时执行一次）
    - cron: '0 */2 * * *' # 每2小时执行一次

  # 允许手动触发
  workflow_dispatch:
    inputs:
      task:
        description: '选择要执行的任务'
        required: true
        type: choice
        options:
          - 'test_message'      				#【T01】手动推送微信消息
          - 'test_new_stock'    			#【T07】手动推送新股信息
          - 'test_new_stock_listings'		#【T08】手动推送新上市交易股票信息
          - 'test_stock_pool'    			#【T04】手动推送当前股票池
          - 'test_execute'				#【T05】手动执行策略并推送结果
          - 'test_reset'					#【T06】手动重置所有仓位（测试用）
          - 'test_arbitrage'				#【T09】手动套利扫描
          - 'run_new_stock_info'			#每日 9:35 新股信息推送
          - 'push_strategy'				#计算策略信号并推送到企业微信
          - 'update_stock_pool'			#每周五16:00北京时间更新ETF股票池（5只稳健仓 + 5只激进仓）
          - 'crawl_daily'					#日线数据爬取任务
          - 'crawl_intraday'				#盘中数据爬取任务
          - 'cleanup'					#数据清理任务
          - 'arbitrage-scan'				#定时套利扫描

jobs:
  # 9:31 AM：爬取当天新股申购、新上市股票信息
  run-new-stock-info:
    if: ${{ contains('31 1 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'run_new_stock_info') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
          echo "Is trading day: $(date '+%u')"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'run_new_stock_info' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新新股信息数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "New stock info execution completed successfully!"

  # 9:45 AM：推送新股申购和新上市股票信息
  push-new-stock-info:
    if: ${{ contains('45 1 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'run_new_stock_info') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'run_new_stock_info' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新新股信息 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "New stock info push execution completed successfully!"

  # 9:55 AM：爬取当天ETF交易数据
  crawl-intraday:
    if: ${{ contains('55 1 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'crawl_intraday') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Current UTC hour: $(date -u '+%H')"
          echo "Event schedule: ${{ github.event.schedule }}"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'crawl_intraday' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动爬取盘中数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Intraday crawl execution completed successfully!"

  # 13:00 PM：套利扫描、股票池策略计算与推送
  push-strategy:
    if: ${{ contains('0 5 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'push_strategy') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'push_strategy' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新策略数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Strategy push execution completed successfully!"

  # 13:00 PM：套利扫描
  arbitrage-scan:
    if: ${{ contains('0 5 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'arbitrage-scan') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Manual trigger for arbitrage scan"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'arbitrage-scan' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动更新套利数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Arbitrage scan execution completed successfully!"

  # 16:00 PM：爬取日线数据
  crawl-daily:
    if: ${{ contains('0 8 * * 1-5', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'crawl_daily') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Is weekday? $([ $(date -u '+%u') -le 5 ] && echo 'Yes' || echo 'No')"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'crawl_daily' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动爬取日线数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Daily crawl execution completed successfully!"

  # 00:00 AM：清理旧数据
  cleanup:
    if: ${{ contains('0 16 * * *', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'cleanup') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Cleanup task triggered at $(date -u)"
      
      - name: Run strategy
        env:
          TASK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task || 'cleanup' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TRI_HTM_TOKEN: ${{ secrets.TRI_HTM_TOKEN }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          MESSAGE_FOOTER: ${{ secrets.MESSAGE_FOOTER }}
        run: |
          # 执行主程序
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动清理旧数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "Cleanup execution completed successfully!"

  # 断点续爬任务（每2小时执行一次，仅在非交易时间）
  resume-crawl:
    if: ${{ contains('0 */2 * * *', github.event.schedule) || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'resume_crawl') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if non-trading hours
        id: check_hours
        run: |
          echo "Current UTC time: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Current UTC hour: $(date -u '+%H')"
          utc_hour=$(date -u '+%H')
          beijing_hour=$(( (10#$utc_hour + 8) % 24 ))
          echo "Current Beijing time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Beijing hour: $beijing_hour"
          
          # 判断是否在非交易时间 (18:00-09:00)
          if (( beijing_hour >= 18 || beijing_hour < 9 )); then
            echo "IN_NON_TRADING_HOURS=true"
            echo "IN_NON_TRADING_HOURS=true" >> $GITHUB_ENV
            echo "non_trading_hours=true" >> $GITHUB_OUTPUT
          else
            echo "IN_NON_TRADING_HOURS=false"
            echo "IN_NON_TRADING_HOURS=false" >> $GITHUB_ENV
            echo "non_trading_hours=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run resume crawl (only in non-trading hours)
        if: steps.check_hours.outputs.non_trading_hours == 'true'
        env:
          TASK: resume_crawl
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "自动续爬ETF数据 $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"
      
      - name: Skip resume crawl (during trading hours)
        if: steps.check_hours.outputs.non_trading_hours != 'true'
        run: |
          echo "当前为交易时间 (北京时间 09:00-18:00)，跳过断点续爬任务"
          echo "Beijing time: $(date '+%Y-%m-%d %H:%M:%S')"
